# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Cegep\2\prog\QT_designer\listview_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 422)
        self.listView_Etudiants = QtWidgets.QListView(Dialog)
        self.listView_Etudiants.setGeometry(QtCore.QRect(70, 60, 341, 291))
        self.listView_Etudiants.setObjectName("listView_Etudiants")
        self.pushButton_Quitter = QtWidgets.QPushButton(Dialog)
        self.pushButton_Quitter.setGeometry(QtCore.QRect(180, 360, 121, 41))
        self.pushButton_Quitter.setObjectName("pushButton_Quitter")
        self.label_Liste_Etudiants = QtWidgets.QLabel(Dialog)
        self.label_Liste_Etudiants.setGeometry(QtCore.QRect(70, 20, 111, 21))
        self.label_Liste_Etudiants.setObjectName("label_Liste_Etudiants")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Quitter.setText(_translate("Dialog", "Quitter"))
        self.label_Liste_Etudiants.setText(_translate("Dialog", "Liste des Étudiant.e.s"))
